src/Entity/Reclamation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Reclamation
 *
 * @ORM\Table(name="reclamation", indexes={@ORM\Index(name="id_user", columns={"id_user"})})
 * @ORM\Entity
 */
class Reclamation
{
    /**
     * @var int
     *
     * @ORM\Column(name="numero", type="integer", nullable=false)
     * @ORM\Id

     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $numero;

    /**
     * @var string
     * @Assert\NotBlank(message=" nom doit etre non vide")
     * @ORM\Column(name="nom", type="string", length=255, nullable=false)
     */
    private $nom;

    /**
     * @var string
     * @Assert\NotBlank(message=" prenom doit etre non vide")
     * @ORM\Column(name="prenom", type="string", length=255, nullable=false)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=false)
     * @Assert\NotBlank(message="Email is required")
     * @Assert\Email(message = "The email '{{  }}' is not a valid
    email.")
     */
    private $email;

    /**
     * @var string
     *  @Assert\Length(min=3,minMessage="content length must be greater than 3")
     * @ORM\Column(name="commentaire", type="string", length=255, nullable=false)
     */
    private $commentaire;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateReclamation", type="date", nullable=false)
     */
    private $datereclamation;

    /**
     * @var string
     *
     * @ORM\Column(name="typeReclamation", type="string", length=255, nullable=false)
     */
    private $typereclamation;

    /**
     * @var \Users
     *
     * @ORM\ManyToOne(targetEntity="Users")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_user", referencedColumnName="id_user")
     * })
     */
    private $id_user;

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getDatereclamation(): ?\DateTimeInterface
    {
        return $this->datereclamation;
    }

    public function setDatereclamation(\DateTimeInterface $datereclamation): self
    {
        $this->datereclamation = $datereclamation;

        return $this;
    }

    public function getTypereclamation(): ?string
    {
        return $this->typereclamation;
    }

    public function setTypereclamation(string $typereclamation): self
    {
        $this->typereclamation = $typereclamation;

        return $this;
    }

    public function getId(): ?Users
    {
        return $this->id_user;
    }

    public function setId(?Users $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('commentaire')
            ->add('datereclamation')
            ->add('typereclamation')
            ->add('id_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;
use App\Entity\Reclamation;

use App\Form\Reclamation1Type;
use App\Notification\NouveauCompteNotification;
use App\Form\ReclamationType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\BarChart;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mime\Email;

use App\Repository\ReclamationRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

use Symfony\Component\Form\Form;
/**
 * @Route("/reclamation")
 */
class ReclamationController extends AbstractController
{


    /**
     * @Route("/", name="app_reclamation_index", methods={"GET"})
     */
    public function index(EntityManagerInterface $entityManager,Request $request,PaginatorInterface $paginator): Response
    {
        $donnees = $entityManager
            ->getRepository(Reclamation::class)
            ->findAll();


        $reclamations = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );
        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamations,
        ]);
    }

    /**
     * @Route("/new", name="app_reclamation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager,MailerInterface $mailer): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(Reclamation1Type::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reclamation);
            $entityManager->flush();
            $this->addFlash("success","votre reclamation a ete ajouter");

            $e=$form["email"]->getData();

            $email = (new  TemplatedEmail())
                ->from($e)
                ->to('pegasustravels10@gmail.com')
                ->htmlTemplate('reclamation/mail.html.twig')
                ->subject('🥳 Une nouvelle reclamation est organisé 🥳')

                ->context(['comm'=>$form["commentaire"]->getData(),'typereclamation'=>$form["typereclamation"]->getData()]);


            $mailer->send($email);
            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{numero}", name="app_reclamation_show", methods={"GET"})
     */
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    /**
     * @Route("/{numero}/edit", name="app_reclamation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Reclamation1Type::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{numero}", name="app_reclamation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reclamation->getNumero(), $request->request->get('_token'))) {
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }



    /**
     * @Route("/r/search_event", name="search_event")
     */

    public function search_event(Request $request,NormalizerInterface $Normalizer ): Response
    {
        $repository = $this->getDoctrine()->getRepository(Reclamation::class);
        $requestString = $request->get('searchValue');
        $reclamation = $repository->findType($requestString);
        $jsoncontentc = $Normalizer->normalize($reclamation, 'json', ['groups' => 'posts:read']);
        $jsonc = json_encode($jsoncontentc);
        //   dump($jsonc);
        if ($jsonc == "[]") {
            return new Response(null);
        } else {
            return new Response($jsonc);
        }

    }


    /**
     * @Route("filter", name="filter")
     */
    public function Filter( ReclamationRepository $repo ,Request $request ,PaginatorInterface $paginator) : Response
    {
        $typereclamation= $_GET['typereclamation'];
        $data = $repo->Filter( $typereclamation);
        $reclamation = $paginator->paginate(
            $data, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamation,
        ]);

}


}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'numero': reclamation.numero}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.numero) }}">
    <button class="btn"  style="background-color: white ;margin-bottom: 15px;width: 250px; ">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/reclamation/ajout_reclamation.html.twig
!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nouvelle inscription</title>
</head>
<body>
<h1>Nouveau compte</h1>
<p>Un nouveau compte a été créé</p>
</body>
</html>

templates/reclamation/edit.html.twig
{% extends 'baseFront.html.twig' %}
{% block title %}Edit Reclamation{% endblock %}





{% block body %}

    <div class="container-xxl flex-grow-1 container-p-y">

        <div style="display: flex;align-content: center ;justify-content: center ;margin-top: 100px;padding: 20px ">
        <div class="col-md-6">
            <div class="card mb-4">
                <h1 class="card-header">Modifier Recalamation</h1>
                {{ form_start(form,{'attr': {novalidate: 'novalidate'}} ) }}

                <div class="card-body">
                    <div>
                        <label for="defaultFormControlInput" class="form-label">Nom</label>
                        {{ form_widget(form.nom,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.nom,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label">Prenom</label>
                        {{ form_widget(form.prenom,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.prenom,{'attr':{'class':'text-danger'}}) }}
                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label">Email</label>
                        {{ form_widget(form.email,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.email,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label">Commantaire</label>
                        {{ form_widget(form.commentaire,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.commentaire,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div class="mb-3 row">
                        <label for="html5-date-input" class="col-md-2 col-form-label">DatedeRecalamation</label>
                        <div class="col-md-10">
                            {{ form_widget(form.datereclamation,{'attr':{'class':'form-control'}})}}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">TypeReclamation</label>
                        {{ form_widget(form.typereclamation,{'attr':{'class':'form-control'}})}}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Id</label>
                        {{ form_widget(form.id,{'attr':{'class':'form-control'}})}}

                        </select>
                    </div>
                    <div class="row mb-3" style="margin-left: 250px">

                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary" style="background-color: white ;margin-bottom: 15px;width: 250px;">{{ button_label|default('Update') }}</button>
                            <a type="submit" class="btn btn-primary "style="background-color: white ;margin-bottom: 15px;width: 250px;" href="{{ path('app_reclamation_index') }}">back to list</a>

                        </div>






                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    </div>




    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'baseFront.html.twig' %}
{% block title %} PegasusTravel {% endblock %}
 {% block body %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="front-office/http://webthemez.com" />
    <!-- css -->
    <link href="{{ asset('front-office/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('front-office/css/fancybox/jquery.fancybox.css') }}" rel="stylesheet">
    <link href="{{ asset('front-office/css/flexslider.css') }}" rel="stylesheet" />
    <link href="{{ asset('front-office/css/style.css') }}" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="{{asset('front-office/http://html5shim.googlecode.com/svn/trunk/html5.js')}}"></script>
    <![endif]-->

</head>
<body>




                <li>
                    <img src="/img/slides/2.jpg" alt="" />
                    <div class="flex-caption">
                        <!--  <h3>Enjoy the Journey</h3>
                          <p>Stop worrying and enjoy the trip</p> -->

                    </div>
                </li>
            </ul>
        </div>
        <!-- end slider -->

    </section>


    <section id="content" >
        {% for message in app.flashes('success') %}
        <div class="alert alert-success " style="align-content: center">
            {{ message }}
        </div>
        {% endfor %}
        <div class="col-md-12" >
            <div class="aligncenter"><h2 class="aligncenter">Les Reclamations</h2></div>
            <br/>
        </div>


        <div style=" display: flex;align-content: center ; justify-content: center ; margin-top: 100px ; padding: 20px">
            <div class="row box-section">
                <div class="col-md-5">
                    <div class="container">
                        <div class="row" id="t">
                                <tbody id="all">
                            {% for reclamation in reclamations %}
                                <div class="col-md-4" >
                                    <div class="box-content" style="margin:20px">
                                        <a href="details.html">


                                             <h3 style="color: #0b0b0b">  Nom : <span type="" class="d-print-table-cell" style="color: #0b0b0b">{{ reclamation.nom }}</span></h3>
                                            <h3 style="color: #0b0b0b"> Prenom:  <span class="d-print-table-cell" style="color: #0b0b0b">{{ reclamation.prenom }}</span></h3>

                                            <h3 style="color: #0b0b0b">Email: <span class="d-print-table-cell" style="color: #0b0b0b">{{ reclamation.email }}</span> </h3>
                                            <h3 style="color: #0b0b0b"> Commentaire: <span class="d-print-table-cell"style="color: #0b0b0b">{{ reclamation.commentaire|raw }}</span></h3>
                                            <h3 style="color: #0b0b0b"> TypeReclamation:<span class="d-print-table-cell"style="color: #0b0b0b">{{ reclamation.typereclamation }}</span></h3>
                                            <strong style="color: #0b0b0b" > Date:{{ reclamation.datereclamation ? reclamation.datereclamation|date('Y-m-d') : '' }}</strong>
                                        </a>
                                        <div   style="margin-bottom: 30px ; align-content: center"><a   type="submit" class="btn btn-primary " style="background-color: white ;margin-bottom: 15px;width: 250px;" href="{{ path('app_reclamation_show', {'numero': reclamation.numero}) }}"  >show</a>
                                         <a type="submit" class="btn btn-primary " style="background-color: white;width: 250px;"href="{{ path('app_reclamation_edit', {'numero': reclamation.numero}) }}">edit</a></div>
                                    </div>


                                </div>
                            {% else %}
                                <tr>
                                    <td colspan="8">no records found</td>
                                </tr>
                            {% endfor %}
                             </tbody>


        <tbody id="search">

        </tbody>


                                    </tbody>
                            </table>
                        </div>
                    </div>
                    <a type="submit" class="btn btn-primary "style="background-color: white"   href="{{ path('app_reclamation_index') }} ">back to list</a>
                    <a type="submit" class="btn btn-primary " style="background-color: white" href="{{ path('app_reclamation_new') }}">Create new</a>


                </div>

                </div>



                </div>

                        </div>


    <form action="{{ path("filter") }}" method="get">
        <label>  <input value="" id="typereclamation" name="typereclamation"  class="form-control " placeholder="Votre Type de reclaamtions ... " style="width: 300px"> </label>
        <button class="btn btn-primary" > OK </button>
    </form>
     <div>
     <form class="align-content-center" action="{{ path("search_event") }}" method="get" style="align-items: center">
            <label>  <input type="text" id="search" class="form-control" placeholder="Search">

            </form>


</div>
                    </section>
                </div>
                </div>



</body>







        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="copyright">
                        <p>
                            <!--  <span>&copy; Bootstrap Template 2018 All right reserved. Template By </span><a href="http://webthemez.com/free-bootstrap-templates/" target="_blank">WebThemez</a> -->
                        </p>

                    </div>
                </div>


            </div>
        </div>
    </div>
</footer>
</html>
      <a style="margin: 140px "class="d-print-table-cell"> {{ knp_pagination_render(reclamations) }}</a>


                {% endblock %}

            {% block js %}
<script
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
</script>
</script>
<script>
    $( document ).ready(function() {
        $("#show").keyup(function(e) {
            var value = $(this).val();
            $.ajax({
                url : "{{ path('search_back1') }}",
                method: "GET",
                data: {
                    searchValue: value,
                },
                success : function(data){
                    $('#t tbody#search').empty();
                    if(data){
                        $('#t tbody#all').hide();
                        for (i = 0; i < data.length; i++) {

                            $('#t tbody#search').append('' +
                                '<tr><td> '+data[i].numero+' </td>' +
                                '<tr><td> '+data[i].nom+' </td>' +
                                '<td>'+data[i].prenom+' </td>' +
                                '<td>'+data[i].email+' </td>' +
                                '<td>'+data[i].commentaire+' </td>' +
                                '<td>'+data[i].datereclamation+' </td>' +
                                '<td>'+data[i].typereclamation+' </td>  </tr>');
                        };
                    }
                    else
                    {

                        $('#t tbody#all').show();
                        $('#t tbody#search').empty();
                        $('#t tbody#search').fadeIn('fast');
                    }
                },
            });
            return false;
    </section>


            {% endblock %}

templates/reclamation/new.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}New Reclamation{% endblock %}



{% block body %}
    <h1>Ajouter  Reclamation</h1>
    <div class="container-xxl flex-grow-1 container-p-y">
        <div style="display: flex;align-content: center ;justify-content: center ;margin-top: 100px;padding: 20px ">
            <div class="col-md-6">

                <img src="{{ asset('front-office/img/alo6.gif')  }} "class="img-fluid "style="margin-top: 150px">
            </div>

        <div class="col-md-6">
            <div class="card mb-4">
                <h2 class="card-header" >Ajouter Recalamation</h5>
                {{ form_start(form,{'attr': {novalidate: 'novalidate'}} ) }}

                <div class="card-body">
                    <div>
                        <label for="defaultFormControlInput" class="form-label col-sm-4">Nom</label>
                        <br>
                        {{ form_widget(form.nom,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.nom,{'attr':{'class':'text-danger'}}) }}


                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label col-sm-4">Prenom</label>
                        <br>
                        {{ form_widget(form.prenom,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.prenom,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label col-sm-4">Email</label>
                        <br>
                        {{ form_widget(form.email,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.email,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div>
                        <label for="defaultFormControlInput" class="form-label col-sm-4 " >Commantaire</label>
                        <br>
                        {{ form_widget(form.commentaire,{'attr':{'class':'form-control'}})}}
                        {{ form_errors(form.commentaire,{'attr':{'class':'text-danger'}}) }}

                    </div>
                    <div class="mb-3 row">
                        <label for="html5-date-input" class="col-md-2 col-form-label">DatedeRecalamation</label>
                        <br>
                        <div class="col-md-10">
                            {{ form_widget(form.datereclamation,{'attr':{'class':'form-control'}})}}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">TypeReclamation</label>
                        {{ form_widget(form.typereclamation,{'attr':{'class':'form-control'}})}}
                    </div>
                    <div class="mb-3">
                    <label for="exampleFormControlSelect1" class="form-label col-sm-4">Id</label>
                    {{ form_widget(form.id,{'attr':{'class':'form-control'}})}}

                    </select>
                </div>
                        <div class="row mb-3" style="margin-left: 250px">

                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary "style="background-color: white ;margin-bottom: 20px;width: 250px;" >{{ button_label|default('Save') }}</button>


                            </div>




                            <a type="submit" class="btn btn-primary " style="background-color: white ;margin-bottom: 20px;width: 250px;" href="{{ path('app_reclamation_index') }}">back to list</a>

                </div>

            </div>
        </div>
            {{ form_end(form) }}
    </div>

    </div>


    </div>
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamation</h1>

    <table class="table" border="2"  >
        <tbody>

            <tr>
                <th>Nom</th>
                <td>{{ reclamation.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ reclamation.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ reclamation.email }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ reclamation.commentaire }}</td>
            </tr>
            <tr>
                <th>Datereclamation</th>
                <td>{{ reclamation.datereclamation ? reclamation.datereclamation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Typereclamation</th>
                <td>{{ reclamation.typereclamation }}</td>
            </tr>
        </tbody>
    </table>

    <a type="submit" class="btn btn-primary " style="background-color: white ;margin-bottom: 15px;width: 250px;"href="{{ path('app_reclamation_index') }}">back to list</a>

    <a type="submit" class="btn btn-primary "style="background-color: white ;margin-bottom: 15px;width: 250px;" href="{{ path('app_reclamation_edit', {'numero': reclamation.numero}) }}" >edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}